"""empty message

Revision ID: 29484c439004
Revises: 8a1a5bbee5a0
Create Date: 2023-05-17 14:30:19.932126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29484c439004'
down_revision = '8a1a5bbee5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.drop_constraint('factura_total_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.create_unique_constraint('factura_total_key', ['total'])

    # ### end Alembic commands ###
