"""empty message

Revision ID: 37202a369be9
Revises: 1ce438b58bd1
Create Date: 2023-05-12 17:26:07.882342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37202a369be9'
down_revision = '1ce438b58bd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licores', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('litres',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('licores', schema=None) as batch_op:
        batch_op.alter_column('litres',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
