"""empty message

Revision ID: 8a1a5bbee5a0
Revises: f353189c558a
Create Date: 2023-05-17 14:28:14.522753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a1a5bbee5a0'
down_revision = 'f353189c558a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.drop_constraint('factura_direccion_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('factura', schema=None) as batch_op:
        batch_op.create_unique_constraint('factura_direccion_key', ['direccion'])

    # ### end Alembic commands ###
